[project]
name = "torchmd-net"
description = "TorchMD-NET provides state-of-the-art neural networks potentials for biomolecular systems"
authors = [{ name = "Acellera", email = "info@acellera.com" }]
readme = "README.md"
requires-python = ">=3.8"
dynamic = ["version"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: POSIX :: Linux",
]
dependencies = [
  "h5py",
  # "nnpops",
  "torch>=2.5",
  "torch_geometric",
  "lightning",
  "tqdm",
]

[project.urls]
"Homepage" = "https://github.com/torchmd/torchmd-net"
"Bug Tracker" = "https://github.com/torchmd/torchmd-net/issues"

[project.scripts]
torchmd-train = "torchmdnet.scripts.train:main"

[tool.setuptools_scm]

[tool.setuptools.packages.find]
include = ["torchmdnet*"]

[tool.setuptools.exclude-package-data]
"*" = ["*.c", "*.cpp", "*.h", "*.cuh", "*.cu", ".gitignore"]

[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8", "torch>=2.5"]
build-backend = "setuptools.build_meta"


[tool.cibuildwheel]
# Disable builds which can't support CUDA and pytorch
skip = ["cp38-*", "pp*", "*win32", "*armv7l", "*_i686", "*_ppc64le", "*_s390x", "*_universal2", "*-musllinux_*"]
test-requires = ["pytest", "pytest-xdist"]
test-command = "pytest {project}/tests/test_calculator.py"
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
environment-pass = ["CIBW_ARCHS"]

[tool.cibuildwheel.linux]
before-all = "cibuildwheel_support/prepare_build_environment_linux.sh"
repair-wheel-command = [
  "auditwheel repair --exclude libc10.so --exclude libc10_cuda.so --exclude libtorch.so --exclude libtorch_cuda.so --exclude libtorch_cpu.so --exclude libtorch_python.so -w {dest_dir} {wheel}",
]

[tool.cibuildwheel.windows]
before-all = "bash cibuildwheel_support/prepare_build_environment_windows.sh"

[tool.cibuildwheel.macosx]
repair-wheel-command = [
  "auditwheel repair --exclude libc10.dylib --exclude libc10_cuda.dylib --exclude libtorch.dylib --exclude libtorch_cuda.dylib --exclude libtorch_cpu.dylib --exclude libtorch_python.dylib -w {dest_dir} {wheel}",
]